name: hersafe_sprint1
description: HerSafe Sprint 1 App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Maps
  google_maps_flutter: ^2.14.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.0


  # Location
  geolocator: ^11.0.0

  # Permissions
  permission_handler: ^12.0.1

  # State Management
  provider: ^6.0.5

  # HTTP requests
  http: ^1.2.0

  # Polylines
  flutter_polyline_points: ^2.0.0

  # Linking / calling
  url_launcher: ^6.2.5

  # Share
  share_plus: ^7.0.0

  # SVGs
  flutter_svg: ^2.0.9

  # Notifications
  flutter_local_notifications: ^17.1.0

  # Vibration
  vibration: ^3.1.5

  # Localization
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true

  assets:
    - Assets/Images/hersafe_logo.png
    - Assets/Images/helpline/police.jpg
    - Assets/Images/helpline/ambulance.png
    - Assets/Images/helpline/abuse.png
    - Assets/Images/helpline/women.png
    - Assets/Images/helpline/win.png
    - Assets/Images/helpline/legal.png
    - Assets/Images/helpline/mental.png
    - Assets/Images/helpline/legal_aid.png
    - Assets/Images/helpline/shelter.png

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Images/fonts/Poppins-Regular.ttf
        - asset: Assets/Images/fonts/Poppins-Medium.ttf
        - asset: Assets/Images/fonts/Poppins-Bold.ttf
