name: hersafe_sprint1
description: HerSafe Sprint 1 App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase 
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5

  # Location + Maps
  geolocator: ^11.0.0
  google_maps_flutter: ^2.3.0

  # Permissions
  permission_handler: ^12.0.1

  # State Management
  provider: ^6.0.5

  # HTTP requests (ðŸš¨ needed for Directions API)
  http: ^1.2.0

  # For decoding Google polylines
  flutter_polyline_points: ^2.0.0

  # Linking / calling
  url_launcher: ^6.1.10

  # Share location link / text
  share_plus: ^7.0.0

  # Flutter Material Icons / SVGs
  flutter_svg: ^2.0.9

  # Notifications
  flutter_local_notifications: ^16.1.0

  # Vibration 
  vibration: ^1.8.1

  # Localization
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/hersafe_logo.png
